name: /media/DATA/serbulent/conda_envs/HoloProtRep-AE
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - bleach=3.2.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.0.3
  - openssl=1.0.2u
  - packaging=20.8
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - ptyprocess=0.7.0
  - pygments=2.7.4
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.0

  - nvidia::cudatoolkit  
  - python-dateutil=2.8.1
  - pyzmq=20.0.0
  - qt=5.9.6
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=51.3.3
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
    - blis==0.7.4
    - catalogue==1.0.0
    - chardet==4.0.0
    - cycler==0.10.0
    - cymem==2.0.5
    - fastai==2.2.5
    - fastcore==1.3.19
    - fastprogress==1.0.0
    - idna==2.10
    - install==1.3.5
    - joblib==1.0.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.3
    - murmurhash==1.0.5
    - numpy==1.19.5
    - pandas==1.1.5
    - pillow==8.1.0
    - plac==1.1.3
    - plotly==5.5.0
    - preshed==3.0.5
    - pytorch-lr-finder==0.0.3
    - pytz==2020.5
    - pyyaml==5.4.1
    - requests==2.25.1
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - seaborn==0.11.2
    - spacy==2.3.5
    - srsly==1.0.5
    - tenacity==8.0.1
    - thinc==7.4.5
    - threadpoolctl==2.1.0
    - torch==1.7.1
    - torch-lr-finder==0.2.1
    - torchvision==0.8.2
    - tqdm==4.56.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wasabi==0.8.0
prefix: /media/DATA/serbulent/conda_envs/HoloProtRep-AE
